//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string Donvitinh { get; set; }
        public Nullable<double> Dongia { get; set; }
        public Nullable<int> MaLoaiSP { get; set; }
        public string HinhSP { get; set; }
    
        public virtual LoaiSP LoaiSP { get; set; }
    }
}
